### PR TITLE
Enhancement: repeated test runs (loop)

### PR DESCRIPTION
**Pull request by bbouv**
Add new loop configuration parameter to run tests more than once.
This allows to have only one report for the same tests running
several times.

### CODE REVIEW

**Comment by CsatariGergely** [comment]
@jenisys , @jeamland or @r1chardj0n3s can you please review?

**Comment by jenisys** [comment]
This approach is too simplistic.
You should get the wrong results with reporters (SummaryReporter, JUnitReporter), basically only the results of the last loop iteration. The list of features is handed to the reporters at the end of the test run.

Therefore, for this functionality, the feature objects need to be copied N-1 times and appended to the features list before the test run.

**Review by bittner — CHANGES_REQUESTED** [review]
@jenisys Can you give a concrete example, a code snippet or a reference thereto, on how the copying should be attempted? To incentivise @bbouv to improve the contribution into the right direction.

**Comment by bittner** [comment]
This contribution would also need to extend our documentation.

**Comment by jenisys** [comment]
NOTE: The name/option `--repeat=NUMBER` is more commonly used (at least for me).
It basically provides the functionality of a repeated test runner.

**Comment by jenisys** [comment]
CRITICAL POINTS ARE (or need to be looked over/addressed):
* Test run infrastructure support to duplicate/clone existing model elements (Features)
  REASON: Scenarios may fail in one test run, but not the other (flaky tests).
  Therefore, an entity that provides the test run results for each test run is needed.
* JUnit XML test reports
* JSON formatter output

**Pull request closed without merging**
