### PR TITLE
Fixed keyword translation in Estonian

### PR DESCRIPTION
**Pull request by ookull**
Fixed "Scenario Outline" translation, introduced by importing
https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin-languages.json

### CODE REVIEW

**Comment by jenisys** [comment]
DUE TO: Single-source principle
It is nice but pointless to fix the translated keyword here.

The Cucumber gherkin-languages.json file is the reference. Therefore, you need to provide a pull-request in the Cucumber repository. When the pull-request is merged, drop me a hint and I will update it here.

**Comment by dunossauro** [comment]
Hello @ookull, how you doing?

In the past a made the same mistake. Behave uses the cucumber specification. If you want, you can contrib in this file https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin-languages.json#L1133-L1176 on @cucumber repository. 

If possible, also update the tag for the word "Rule", the word has no translation yet.

**Comment by ookull** [comment]
Cucumber gherkin-languages.json is now updated. https://github.com/cucumber/cucumber/commit/0053777579d4b0d2b1f3f45ad5080586e0bf8b44

**Comment by bittner** [comment]
@jenisys Our [JSON files](https://github.com/behave/behave/tree/master/etc/gherkin) can now be sync'ed with the Cucumber version. :+1:

**Comment by bittner** [comment]
What is the process to sync the files from the Cucumber repositories? Can't we describe that in the related README? So that anyone could run that, and maybe even our test suite would run a verification job to detect a potential delta?

It should be effortless and safe to keep this in sync.

**Comment by jenisys** [comment]
@bittner See: https://github.com/behave/behave/blob/master/etc/gherkin/README.rst and the convert*.py script in the directory. Otherwise, I explain it to you next week. It is currently half-automated.

**Comment by bittner** [comment]
@ookull PR #887 will add instructions on to update the Gherkin language specification in a scripted fashion.

If you want to follow those instructions to regenerate the two files that need updating, and update this PR with that, we'd be able to merge your contribution. Do you want to give that a shot? :100:

**Comment by bittner** [comment]
@ookull Want to give it a try? See the [latest docs](https://behave.readthedocs.io/en/latest/contributing.html) for details.

**Comment by ookull** [comment]
> @ookull PR #887 will add instructions on to update the Gherkin language specification in a scripted fashion.
> 
> If you want to follow those instructions to regenerate the two files that need updating, and update this PR with that, we'd be able to merge your contribution. Do you want to give that a shot? 100

Regenerated files, instructions are OK. I am not able to update PR as my fork of repository is deleted. Is this OK to create new PR or is it possible to update current PR?

**Comment by bittner** [comment]
> Regenerated files, instructions are OK. I am not able to update PR as my fork of repository is deleted. Is this OK to create new PR or is it possible to update current PR?

You should be able to check out this PR directly from GitHub even if you have your local version deleted. See GitHub's [official documentation](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally) for details. Then you should be able to continue just as normal. Please give it a try!

**Comment by ookull** [comment]
> > Regenerated files, instructions are OK. I am not able to update PR as my fork of repository is deleted. Is this OK to create new PR or is it possible to update current PR?
> 
> You should be able to check out this PR directly from GitHub even if you have your local version deleted. See GitHub's [official documentation](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally) for details. Then you should be able to continue just as normal. Please give it a try!

The final step in this instruction is "Create a new pull request with your new branch". Anyway I have no permission to push your repository (`fatal: unable to access 'https://github.com/behave/behave.git/': The requested URL returned error: 403`). Still thinking that new PR is a solution.

**Comment by jenisys** [comment]
**CHANGES INTEGRATED INTO:** behave 1.2.7.dev2
Changes contained in newest update of "gherkin_languages.json" from Cucumber repository (PR #895, LAST COMMIT: 2021-01-07).

@ookull Thank you for your contribution (and patience).

**Pull request closed without merging**
