### PR TITLE
Add python 3.5 to the list of python versions for Travis

### PR DESCRIPTION
**Pull request by hockeybuggy**
This PR adds python 3.5 to the list of interpreters the tests are run against.

### CODE REVIEW

**Comment by hockeybuggy** [comment]
It seems to be [failing here](https://github.com/hockeybuggy/behave/blob/6f5a8fe9da6b109cf83e4d3e960853331b03de81/test/test_runner.py#L180).

When I run it locally: 

```python
file = "/Users/douglas/devel/behave/test/test_runner"
info = "behave runner is masking context attribute 'thing' orignally set in stack_frame = traceback.extract_stack(limit=2)[0] (/Users/douglas/devel/behave/behave/runner.py:232)"
```

**Comment by hockeybuggy** [comment]
It looks like its related to the new object `FrameSummary` in the [traceback module](https://docs.python.org/3.5/library/traceback.html#traceback.FrameSummary). That's as far as I have gotten so far.

**Comment by hockeybuggy** [comment]
I don't think that this behaviour change is damaging. I removed the assertions. Feel free to weigh in if anyone thinks otherwise. :smile:

**Comment by jenisys** [comment]
DONE (thanks for the work).
The assertion problems seem to be related with python 3.5.0.
The problem resolves itself in thin air if you use python 3.5.1 explicitly (or the newer nightly build).

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0

**Comment by hockeybuggy** [comment]
Thanks @jenisys

**Pull request closed without merging**
