### PR TITLE
Add parallelism for scenarios and/or features.

### PR DESCRIPTION
**Pull request by tokunbo**
Okay, reduced the pull-request into something reasonable! -^_^-
Just a few commits with only my changes, instead of that 250+ commits PR from before that was too far behind this master repo.

### CODE REVIEW

**Comment by skovhus** [comment]
Any news on this? Really missing this feature...

**Comment by tokunbo** [comment]
@skovhus  Note that the parallel fork still lives on:

    https://github.com/tokunbo/behave-parallel/tree/upstreamsync 

Anyone is welcome to attempt to get it merged here, or ridicule it, or use it as-is, or whatever. :-)

**Comment by s1ider** [comment]
@skovhus So far you can small script like this https://gist.github.com/s1ider/f13c2f163282dbec7a61 to run features in parallel mode.

**Comment by tokunbo** [comment]
......何に
shockface

**Comment by carlosmmelo** [comment]
nice @s1ider , however not sure why is not executing the scenarios:

```
export BASE_URL='http://localhost:9000' API_URL='http://localhost:8081'; python behave_parallel.py 
[INFO     2015-12-07 17:28:29,738] Found 44 features
. 
.
.
accounts.feature                                  : ok
admin_visibility.feature                          : ok
... etc etc etc

**Comment by remcowesterhoud** [comment]
@s1ider I've modified your gist so it'd work in Python3 and with userdata.
https://gist.github.com/remcowesterhoud/f581b6b69587832da41507ab369f8b3c

**Comment by dbrock** [comment]
Does anyone know what the problem is?

**Comment by vishalm** [comment]
I attempted this : https://github.com/vishalm/behave_parallel_demo
Able to execute with behave-parallel but waiting for this pull request

**Comment by i4s-pserrano** [comment]
@s1ider @remcowesterhoud I've modified your gist to enable parallel scenario with timeout option for each scenario. https://gist.github.com/i4s-pserrano/f18fc8879c2b890270c34e98cfed4d94

**Comment by laripappa** [comment]
@vishalm Was this PR merged into master already? If so, I wanna try this to speed up my test!

**Comment by vishalm** [comment]
I haven't raised any PR

**Comment by kn-neeraj** [comment]
Is this merged to master?

**Pull request closed without merging**
