### PR TITLE
Html formatter

### PR DESCRIPTION
**Pull request by schidlo**
I'd like to continue with what @vrutkovs began. I updated his branch to current master and resolved issues. This should be working solution for html formatter. The original pull request (still  opened) is [#340](https://github.com/behave/behave/pull/340)
The issue which was about adding html formatter is this: [#25](https://github.com/behave/behave/issues/25)
I'm not sure what was missing or wrong with the original issue/PR, but I'd like to work on it to bring html formatter to upstream.

### CODE REVIEW

**Comment by jenisys** [comment]
@schidlo 
Thx, I will have a look.

Another solution could to be to provide the HTML formatter as own small project / python module as project under [behave-contrib](https://github.com/behave-contrib) at let it evolve there.

**Comment by schidlo** [comment]
Hi, what's the chance that this will get approved?

Also I'm not sure how could I convert the HTML formatter to be a standalone project/module in [behave-contrib](https://github.com/behave-contrib) is there some document which I could follow? Thank you for answers in advance.

**Comment by jenisys** [comment]
@schidlo 
Yes, you can (and I help you with it; currently I would suggest this approach).
It is just a python package that needs to be provided.

`behave` supports pluggable formatters.
Therefore, you just need to provide a python package, like `behave_contrib_html_formatter`, (meaning: you need a `setup.py` script) and provide it on https://pypi.org .

Then everybody can install and use it, like:

```ini
# -- FILE: behave.ini
# Define ALIAS for HtmlFormatter.
[behave.formatters]
html = behave_contrib_html_formatter:HtmlFormatter
```
and use it with `behave` like:

```console
$ behave -f html -o report.html features
...
# -- NOTE: HTML report is written to "report.html".
```

**Comment by ivan-chernyavsky** [comment]
Hi. I've manually applied your changes from html_formatter branch and got regressions when running with "-f html" for steps like the following one:

@then(u'last command return value is {retval:d}')
def step_impl(context, retval):
    assert context.subprocess_retval == retval

Note the integer type for "retval" argument here. Looks like you are force-converting it to a string in html.py:

                 if isinstance(argument.value, six.integer_types):
                    argument.value = str(argument.value)

**Comment by jenisys** [comment]
Reopen.

**Comment by schidlo** [comment]
Hi, I went ahead and created behave-html-formatter module which adds html formatter.
My git repo: <https://github.com/schidlo/behave-html-formatter>
Pypi: <https://pypi.org/project/behave-html-formatter/>
When it will be ready I will move it to <https://github.com/behave-contrib> if you will agree.

Only problem which I have with this approach right now is that embedding doesn't work. We use it quite a lot and when you look to changes in this PR you will find function embed in runner's context which implements it.

Should I create issue for that or PR? I suppose that it can't be added by formatter module, right?

**Comment by jenisys** [comment]
Reopen

**Comment by jenisys** [comment]
@schidlo 
Sorry, I must have overlooked your note. I will try to look at it in the next few days.

**Comment by bittner** [comment]
Hi @schidlo, sorry for the long wait (only 2 years!)

I'm trying out [your package](https://pypi.org/project/behave-html-formatter/) from PyPI with the integration [mentioned in your README)](https://github.com/schidlo/behave-html-formatter#html-formatter-for-behave), and it works pretty well!

I would vote for including it in / transfering it to [behave-contrib](https://github.com/behave-contrib).

It _might_ be valuable to directly include the formatter in Behave, but from the sheer size of the implementation I find this problematic. If we want to promote or make it easy to include this formatter with a Behave installation I'd suggest to instead add it as an optional, extra dependency, e.g.

```python
# FILE: setup.py
...
    extras_require={
        'html': ["behave-html-formatter"],
...
```
In this case we may want to consider implementing some kind of auto-detection for those formatters, to avoid cumbersome setup instructions and puzzled users.

**Comment by bittner** [comment]
> Only problem which I have with this approach right now is that embedding doesn't work. \[...\] in this PR you will find function embed in runner's context which implements it.

@schidlo Can you open an issue for this, with a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), please?

**Comment by bittner** [comment]
Following up on my [thinking-aloud 10 days ago](#issuecomment-736841760):

@schidlo I have created the [behave-contrib/behave-html-formatter](https://github.com/behave-contrib/behave-html-formatter) project, pushed your repository and invited you as a maintainer. I hope that's fine for you. If you'd rather want to move (aka "transfer ownership" of) your project to @behave-contrib please let me know. – Welcome to the team!

**Comment by bittner** [comment]
Created https://github.com/behave-contrib/behave-html-formatter/issues/5 to cover my [comment above](#issuecomment-736841760). :heavy_check_mark:

**Comment by bittner** [comment]
@vrutkovs Should I also add you as a maintainer of [behave-contrib/behave-html-formatter](https://github.com/behave-contrib/behave-html-formatter)?

**Comment by schidlo** [comment]
> Following up on my [thinking-aloud 10 days ago](#issuecomment-736841760):
> 
> @schidlo I have created the [behave-contrib/behave-html-formatter](https://github.com/behave-contrib/behave-html-formatter) project, pushed your repository and invited you as a maintainer. I hope that's fine for you. If you'd rather want to move (aka "transfer ownership" of) your project to @behave-contrib please let me know. – Welcome to the team!

I think that it makes sense to develop directly in behave-contrib repo. And it was my initial goal. So as long as I will be able to merge and commit to the project the behave-contrib is the place where I will continue with development.

**Comment by bittner** [comment]
Thanks Petr! You've probably see that we've moved ahead in the meantime. So, if you want you can pull in the additional changes to your personal copy.

It probably doesn't make sense anymore now to move your repository into the @behave-contrib organization, does it? I hope that's fine for you.

**Pull request closed without merging**
