### PR TITLE
config: options for path to environment file and steps directories

### PR DESCRIPTION
**Pull request by todfreed**
Makes it possible for behave to use steps and environment spread across
directories, rather than all being in the same tree

### CODE REVIEW

**Comment by jenisys** [comment]
Sorry, that is the wrong way to go in my opinion.

It is already possible to use steps from multiple directories. You just need to import the other steps files in one file that is in  the steps directory. The other files must be reachable via the python search path.

SEE ALSO:
* [features/step.use_step_library.feature](https://github.com/behave/behave/blob/master/features/step.use_step_library.feature)

**Comment by todfreed** [comment]
That doesn't cover this need, because you would have to know which files / steps to import. In contrast, to use steps from the steps directory, you don't have to do anything - behave finds them automatically.

If we don't have the autodiscover capability for multiple directory trees of steps in behave, then I have to implement the discovery of steps myself (and so do other users). This is the kind of thing that really should be implemented in behave proper.

**Comment by jenisys** [comment]
Sorry, I disagree. You need to be in control when you import steps. In addition, you can solve this problem on your own. For example, extend the python search path in "features/environment.py" by using the userdata concept.

**Comment by jenisys** [comment]
See comment on pull #170 (basic support provided for steps).

**Pull request closed without merging**
