### PR TITLE
add custom runner support

### PR DESCRIPTION
**Pull request by will-yangsg**
add custom runner support.
We need this feature to implement parallel BDD testing.

### CODE REVIEW

**Comment by kingbuzzman** [comment]
There is another PR that does the same thing https://github.com/behave/behave/pull/795

**Comment by will-yangsg** [comment]
> There is another PR that does the same thing #795

Great, we really need this feature.

**Comment by kingbuzzman** [comment]
@will-yangsg You and me both.

**Comment by bittner** [comment]
Superseded by #795.

Thank you for attempting to solve this issue with this PR, @will-yangsg! :trophy:

**Pull request closed without merging**
