### PR TITLE
Adapt wording in install.rst

### PR DESCRIPTION
**Pull request by charleswhchan**
Update the comment to make sure they are consistent with one another. 

Choices were either:
- New behave installation, upgrade behave installation; or
- New installation, upgrade installation

Since it's pretty obvious we are referring to behave in this context, I picked the latter.

### CODE REVIEW

**Comment by charleswhchan** [comment]
@jenisys: Could you please review this PR?

**Comment by mixxorz** [comment]
I have to ask. What prompted you to send two separate PRs changing one line of documentation? You didn't even provide a description of what you were fixing. Ditto for #338

**Comment by charleswhchan** [comment]
@mixxorz Some teams prefer to have clearly delineated changes be submitted as separated PRa. I am not sure about the the rules for behave. If you prefer, I can combine them together.

Forgot to add in the description as I was making a quick edit thru the Github web UI. I will update.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0

**Comment by charleswhchan** [comment]
Thanks @jenisys

**Pull request merged**
