### PR TITLE
Add the --order option to behave

### PR DESCRIPTION
**Pull request by koenbollen**
Hello Behave peeps,

Thanks for this project, we really like it and are using it a lot. There is, however, a feature missing that we at [Blendle](https://blendle.com) would really like: `--order random`

We mostly do Ruby development using [cucumber](https://github.com/cucumber/cucumber/) and we always run our tests in a random order. This lets us find a few bugs and forces us the make each scenario completely isolated.

This pull-request adds the `--order TYPE[:SEED]` option to the behave command. Possible types are `defined`(default) and `random`. When using the random order you have the option to pass along a set seed to reproduce issues in a previous run.

Hope you like the change! 
Cheers,
—Koen Bollen

### CODE REVIEW

**Comment by koenbollen** [comment]
Hey! Quick question: What's the average timetable on PR's like this one?

**Comment by koenbollen** [comment]
I'm postponing rebasing the branch until it's accepted by the author and ready to be merged. Which I hope is soon. 😉

**Comment by eterps** [comment]
I'd love to see this merged :+1:

**Comment by hudrogen** [comment]
@jenisys Are you going to merge it to master?

**Comment by anneschuth** [comment]
yes please!

**Comment by jenisys** [comment]
The functionality will be considered after the next release. Note that an similar proposal already exists (see #393).

**Comment by koenbollen** [comment]
Cool. I noticed #393 after I opened this pull-request. 😅  The advantage of this version is the output of the used seed which can be reused when tracking down a bug which only occurs in a specific order.
Would love to see this in a release.

**Comment by eterps** [comment]
Any news on this?

**Comment by koenbollen** [comment]
@jenisys Any indication on if and when this could be merged? Otherwise I'd like to close the PR to cleanup my pull-requests list. 🙂

**Comment by koenbollen** [comment]
I'm closing this PR, let me know when you have time to potentially pick this up again. I wont delete the branch.
Cheers!

**Comment by eterps** [comment]
:-(

**Pull request closed without merging**
