### PR TITLE
Remove deprecated U mode for Python 3 compatibility.

### LINKED ISSUE #813: "U" mode is no longer accepted from Python 3.9
https://github.com/behave/behave/blob/80c1e97acdd3251dc291fbb8d1d02c774d3f6d2d/behave/json_parser.py#L36

https://github.com/python/cpython/pull/16959

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #813

### CODE REVIEW

**Comment by jenisys** [comment]
Sorry, works for me is not works for everyone.
Python2 is currently still supported.

**Comment by tirkarthi** [comment]
I don't get your comment. This change is backwards compatible with Python 2. Python 2 is officially not supported and has reached end of life by Jan 2020.

**Comment by jenisys** [comment]
But behave still supports it.
I am not breaking stuff that was working in the past for other people.

**Comment by tirkarthi** [comment]
This will work on both Python 2 and 3. It won't break anything.

**Comment by bittner** [comment]
@jenisys Can you explain why this change would break backwards compatibility?

@tirkarthi Can you explain why this change will _not_ break backwards compatibility?

**Comment by tirkarthi** [comment]
@bittner  The flag "U" is used in Python 2 for universal newlines. In Python 3 it's made default and hence it was deprecated for removal : https://docs.python.org/3/library/functions.html#open . see also https://stackoverflow.com/questions/56791545/what-is-the-non-deprecated-version-of-open-u-mode . So "rU" will work with Python 2 and using only "r" will help Python 3.9 compatibility. I have used six to ensure the relevant flag is passed. As a note for helping modules to migrate to Python 2 this was change was reverted to be introduced in Python 3.10 easing the compatibility concerns for libraries. I have deleted the fork since the PR was closed.

Cpython issue : https://bugs.python.org/issue37330
Reversion to be introduced in Python 3.10 : https://github.com/python/cpython/commit/942f7a2dea2e95a0fa848329565c0d0288d92e47

Thanks

**Pull request closed without merging**
