### PR TITLE
Update documentation related to Django (behave-django)

### PR DESCRIPTION
**Pull request by bittner**
Reflect the current implementation of `behave-django`, and fix a markup issue.

The documentation about Django integration [online at the moment](http://behave.readthedocs.org/en/latest/django.html) is terribly outdated. Can we release it, so Django developers could profit (avoiding them to go wrong ways before finding the easy solution)?

### CODE REVIEW

**Comment by bittner** [comment]
*ping*  @jenisys Any chance this is going to be merged?

**Comment by jenisys** [comment]
:smile: Yes, it is on the list.

**Comment by bittner** [comment]
*ping*  @jenisys Any status update of "the list"?

In April [PyCon 7](https://www.pycon.it/en/) takes place in Florence, Italy. It runs a [dedicated Django track](https://www.pycon.it/p3/schedule/pycon7/). Would be nice if we some released up-to-date documentation of "the state of BDD and Django" until then.

**Comment by bittner** [comment]
*ping*  @jenisys Would it be okay to merge these changes?

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6.dev0

**Comment by bittner** [comment]
Thank you!

Can you make an in-between update of the online docs? (Or when can we expect your planned 1.3.0 release?)

**Comment by jenisys** [comment]
SEE:
* http://python-behave.readthedocs.org/en/latest/django.html
* https://readthedocs.org/projects/python-behave/

**Comment by jenisys** [comment]
Otherwise, I expect to release 1.3.0 approx. in mid April. I need to fix some problems first (unicode-related, etc.).

**Pull request merged**
