### PR TITLE
Add Flask integration chapter to documentation

### LINKED ISSUE #521: Extension request: behave-flask
Are you planning to implement an integration into flask comparable with [behave-django](https://github.com/behave/behave-django)? I would be interested in contribution.

### PR DESCRIPTION
**Pull request by bittner**
This PR:

- adds a new chapter "Flask Test Integration" with boilerplate code,
- and moves general hints on BDD testing to a separate chapter,
- plus points out to the "More Infos" chapter.

As a bonus a regression is fixed: The disappearing of "tox.ini" from the "behave" chapter.

Fixes #521.

### CODE REVIEW

**Comment by bittner** [comment]
@jenisys This PR is only documentation and could easily be merged. Thanks!

**Comment by bittner** [comment]
@jenisys Anything else needed to make you push the merge button?

**Comment by bittner** [comment]
:bell: @jenisys Please push the merge button! It's safe!

**Comment by bittner** [comment]
This PR also addresses https://github.com/behave/behave/pull/429#issuecomment-214872745 by introducing a new chapter on "Practical Tips".

**Comment by bittner** [comment]
@jenisys Please merge! People are waiting for a Flask chapter to arrive, I feel.

**Comment by jenisys** [comment]
INTEGRATED INTO: behave-1.2.6-dev0
Thx

**Comment by bittner** [comment]
:champagne: Yay! :tada: 

Thank you, Jens!

**Comment by bittner** [comment]
Oh, I figured you changed the URL for the Django chapter. It's now available at _.../usecase_django.html_, so we need to update our references in the README and docs of [behave-django](https://github.com/behave/behave-django/pull/50).

**Pull request merged**
